const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();tg.setHeaderColor('#080b12');tg.setBackgroundColor('#080b12')}
const $=s=>document.querySelector(s);let DATA=null;let active='overview';
const params=new URLSearchParams(location.search);const fixture=params.get('fixture')||tg?.initDataUnsafe?.start_param||'';
function esc(v){return String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function pct(v){return v==null?'—':`${Math.round(Number(v))}%`}
function num(v){return v==null?'—':Number(v).toFixed(2)}
function resultClass(x){return x==='W'?'w':x==='L'?'l':x==='D'?'d':''}
function winner(p){const vals=[['HOME',p?.home],['DRAW',p?.draw],['AWAY',p?.away]].filter(x=>x[1]!=null).sort((a,b)=>b[1]-a[1]);return vals[0]||null}
function render(tab){active=tab;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(!DATA)return;const d=DATA;let h='';
if(tab==='overview'){const p=d.prediction||{};const win=winner(p);const advice=p.advice||'Недостаточно данных для вывода';const modelled=win&&p.home!=null&&p.draw!=null&&p.away!=null;h=`<div class="grid"><div class="card hero-signal wide"><div class="signal-line"><div><span class="label">RUSTAM SIGNAL ENGINE</span><div class="signal-title">${esc(advice)}</div><p class="signal-copy">${esc(p.note||'Аналитика строится только на доступных данных API-Football. Отсутствующие значения не подменяются.')}</p></div>${modelled?`<span class="signal-badge">TOP SIGNAL · ${esc(win[0])}</span>`:''}</div><div class="prob-grid"><div class="prob ${win?.[0]==='HOME'?'primary':''}"><b>${pct(p.home)}</b><span>${esc(d.home?.name||'HOME')}</span></div><div class="prob ${win?.[0]==='DRAW'?'primary':''}"><b>${pct(p.draw)}</b><span>DRAW</span></div><div class="prob ${win?.[0]==='AWAY'?'primary':''}"><b>${pct(p.away)}</b><span>${esc(d.away?.name||'AWAY')}</span></div></div></div><div class="card"><span class="label">EXPECTED GOALS</span><div class="big">${num(p.homeGoals)} : ${num(p.awayGoals)}</div><div class="row"><span>Model</span><b>${p.homeGoals!=null?'available':'no data'}</b></div></div><div class="card"><span class="label">GOAL LINE</span><div class="big">${esc(p.underOver||'—')}</div><div class="row"><span>BTTS</span><b>${esc(p.btts||'—')}</b></div></div><div class="card"><span class="label">DATA QUALITY</span><div class="big">${quality(d)}%</div><div class="bar-list"><div><div class="bar-head"><span>Sources ready</span><b>${readySources(d)}/5</b></div><div class="track"><div class="fill good" style="width:${quality(d)}%"></div></div></div></div></div><div class="card wide"><div class="section-head"><h3>Ключевые факторы</h3><span>DERIVED FROM DATA</span></div><div class="factor-list">${factors(d)}</div></div></div>`}
if(tab==='form'){h=`<div class="grid"><div class="card wide"><div class="section-head"><h3>Последние 5 матчей</h3><span>RECENT FORM</span></div><div class="formrow">${teamForm(d.home)}${teamForm(d.away)}</div></div><div class="card"><span class="label">${esc(d.home?.name)} · AVG GOALS</span><div class="big">${num(d.home?.avgGoals)}</div><div class="row"><span>BTTS</span><b>${pct(d.home?.btts)}</b></div></div><div class="card"><span class="label">${esc(d.away?.name)} · AVG GOALS</span><div class="big">${num(d.away?.avgGoals)}</div><div class="row"><span>BTTS</span><b>${pct(d.away?.btts)}</b></div></div></div>`}
if(tab==='h2h'){h=`<div class="grid"><div class="card wide"><div class="section-head"><h3>Head to Head</h3><span>${d.h2h?.count||0} MATCHES</span></div>${rows(d.h2h?.rows,'История H2H недоступна для этого матча.')}</div></div>`}
if(tab==='table'){h=`<div class="grid"><div class="card wide"><div class="section-head"><h3>Положение в лиге</h3><span>SEASON TABLE</span></div>${tableTeam(d.home?.standing)}${tableTeam(d.away?.standing)}</div></div>`}
if(tab==='odds'){h=`<div class="grid"><div class="card wide"><div class="section-head"><h3>Market snapshot</h3><span>LIVE SOURCE</span></div>${rows(d.odds?.rows,'Коэффициенты не доступны для этого матча.')}</div></div>`}
if(tab==='risk'){const r=d.risk||{};h=`<div class="grid"><div class="card hero-signal wide"><span class="label">RISK ENGINE</span><div class="signal-title">${esc(r.level||'UNDEFINED')}</div><p class="signal-copy">${esc(r.reason||'Недостаточно подтверждённых данных.')}</p></div><div class="card wide"><div class="section-head"><h3>Источники данных</h3><span>5 CHECKS</span></div>${source('Prediction engine',d.sources?.prediction)}${source('Recent form',d.sources?.form)}${source('H2H',d.sources?.h2h)}${source('League table',d.sources?.standings)}${source('Odds',d.sources?.odds)}</div></div>`}
$('#content').innerHTML=h||'<div class="empty">Раздел пока пуст.</div>'}
function teamForm(t){if(!t)return '<div class="formteam"><b>Нет данных</b></div>';const r=(t.results||[]).map(x=>`<span class="result ${resultClass(x)}">${x}</span>`).join('');return `<div class="formteam"><b>${esc(t.name)}</b><div class="results">${r||'—'}</div><div class="row"><span>AVG goals</span><b>${num(t.avgGoals)}</b></div><div class="row"><span>BTTS</span><b>${pct(t.btts)}</b></div></div>`}
function rows(arr,empty){if(!arr?.length)return `<div class="empty">${empty}</div>`;return arr.map(x=>`<div class="row"><span>${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('')}
function tableTeam(s){if(!s)return '<div class="empty">Позиция команды в таблице недоступна.</div>';return `<div class="table-team"><span class="rank">#${esc(s.rank)}</span><div><b>${esc(s.team)}</b><small>League position</small></div><strong>${esc(s.points)} pts</strong></div>`}
function source(n,v){return `<div class="row"><span>${n}</span><b class="${v?'green':'red'}">${v?'READY':'NO DATA'}</b></div>`}
function readySources(d){return Object.values(d.sources||{}).filter(Boolean).length}
function quality(d){return Math.round(readySources(d)/5*100)}
function factors(d){const p=d.prediction||{},out=[];if(p.advice)out.push(['🎯','Prediction engine',p.advice]);if(d.home?.results?.length&&d.away?.results?.length)out.push(['📈','Recent form',`${d.home.results.join(' · ')}  vs  ${d.away.results.join(' · ')}`]);if(d.home?.standing&&d.away?.standing)out.push(['🏆','League position',`#${d.home.standing.rank} vs #${d.away.standing.rank}`]);if(d.h2h?.count)out.push(['🤝','H2H sample',`${d.h2h.count} previous meetings`]);if(d.odds?.rows?.length)out.push(['💰','Market',`${d.odds.rows.length} market lines available`]);if(!out.length)return '<div class="empty">Недостаточно данных для факторов.</div>';return out.slice(0,5).map(x=>`<div class="factor"><div class="factor-icon">${x[0]}</div><div><b>${esc(x[1])}</b><span>${esc(x[2])}</span></div><strong>✓</strong></div>`).join('')}
async function load(){if(!fixture){$('#content').innerHTML='<div class="error-box"><b>Матч не выбран</b>Открой Mini App из Telegram после выбора матча.</div>';return}$('#content').innerHTML='<div class="loading"><div class="spinner"></div><b>RUSTAM ENGINE</b><span>Собираем матч-пакет…</span></div>';try{const r=await fetch(`/api/match?fixture=${encodeURIComponent(fixture)}`,{cache:'no-store'});const body=await r.json().catch(()=>({}));if(!r.ok)throw Error(body.error||`API ${r.status}`);DATA=body;updateHeader();render(active)}catch(e){$('#content').innerHTML=`<div class="error-box"><b>Не удалось собрать матч-пакет</b>${esc(e.message||'Unknown error')}<br><br><small>Нажми ↻, чтобы повторить запрос.</small></div>`}}
function updateHeader(){if(!DATA?.fixture)return;const f=DATA.fixture;$('#title').textContent=`${f.home} — ${f.away}`;$('#subtitle').textContent=f.league||'Football Intelligence';$('#league').textContent=(f.league||'FOOTBALL').toUpperCase();$('#homeName').textContent=f.home;$('#awayName').textContent=f.away;$('#homeLogo').src=f.homeLogo||'';$('#awayLogo').src=f.awayLogo||'';$('#kickoff').textContent=f.time||'—';$('#dateText').textContent=f.status||'PRE-MATCH';$('#venue').textContent=f.venue||'Venue data unavailable';$('#fixtureId').textContent=`FIXTURE ${f.id}`}
document.querySelector('#tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b)render(b.dataset.tab)});$('#refresh').onclick=load;load();
