const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();tg.setHeaderColor('#07090f');tg.setBackgroundColor('#07090f')}
const $=s=>document.querySelector(s);let DATA=null;let active='prediction';
const params=new URLSearchParams(location.search);const fixture=params.get('fixture')||tg?.initDataUnsafe?.start_param||'';
function esc(v){return String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function pct(v){return v==null?'—':`${Math.round(Number(v))}%`}
function num(v){return v==null?'—':Number(v).toFixed(2)}
function resultClass(x){return x==='W'?'w':x==='L'?'l':x==='D'?'d':''}
function render(tab){active=tab;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(!DATA){return}const d=DATA;let h='';
if(tab==='prediction'){const p=d.prediction||{};h=`<div class="grid"><div class="card signal wide"><span class="label">RUSTAM MODEL</span><h2>${esc(p.advice||p.verdict||'Недостаточно данных')}</h2><p>${esc(p.note||'Модель использует доступные данные API-Football. Ничего не подставляется искусственно.')}</p><div class="metrics"><div class="metric"><b>${pct(p.home)}</b><span>HOME</span></div><div class="metric"><b>${pct(p.draw)}</b><span>DRAW</span></div><div class="metric"><b>${pct(p.away)}</b><span>AWAY</span></div></div></div><div class="card"><span class="label">EXPECTED GOALS</span><div class="big">${num(p.homeGoals)} : ${num(p.awayGoals)}</div></div><div class="card"><span class="label">GOAL LINE</span><div class="big">${esc(p.underOver||'—')}</div></div><div class="card"><span class="label">BTTS</span><div class="big">${esc(p.btts||'—')}</div></div></div>`}
if(tab==='form'){h=`<div class="grid"><div class="card wide"><h2>Последние матчи</h2><div class="formrow">${teamForm(d.home)}${teamForm(d.away)}</div></div><div class="card"><span class="label">HOME AVG GOALS</span><div class="big">${num(d.home?.avgGoals)}</div></div><div class="card"><span class="label">AWAY AVG GOALS</span><div class="big">${num(d.away?.avgGoals)}</div></div></div>`}
if(tab==='h2h'){h=`<div class="grid"><div class="card wide"><h2>Head to Head</h2>${rows(d.h2h?.rows,'Недостаточно H2H данных')}</div><div class="card"><span class="label">H2H SAMPLE</span><div class="big">${esc(d.h2h?.count||0)}</div></div></div>`}
if(tab==='table'){h=`<div class="grid"><div class="card wide"><h2>Позиции в лиге</h2>${tableTeam(d.home?.standing)}${tableTeam(d.away?.standing)}</div></div>`}
if(tab==='odds'){h=`<div class="grid"><div class="card wide"><h2>Market</h2>${rows(d.odds?.rows,'Коэффициенты не доступны для этого матча')}</div></div>`}
if(tab==='risk'){h=`<div class="grid"><div class="card signal wide"><span class="label">RISK ENGINE</span><h2>${esc(d.risk?.level||'НЕ ОПРЕДЕЛЁН')}</h2><p>${esc(d.risk?.reason||'Недостаточно подтверждённых источников для оценки риска.')}</p></div><div class="card"><span class="label">DATA SOURCES</span>${source('Prediction',d.sources?.prediction)}${source('Form',d.sources?.form)}${source('H2H',d.sources?.h2h)}${source('Standings',d.sources?.standings)}${source('Odds',d.sources?.odds)}</div></div>`}
$('#content').innerHTML=h||'<div class="empty">Нет данных</div>'}
function teamForm(t){if(!t)return '<div class="formteam"><b>—</b><div class="results"></div></div>';let r=(t.results||[]).map(x=>`<span class="result ${resultClass(x)}">${x}</span>`).join('');return `<div class="formteam"><b>${esc(t.name)}</b><div class="results">${r||'—'}</div><div class="row"><span>AVG goals</span><b>${num(t.avgGoals)}</b></div><div class="row"><span>BTTS</span><b>${pct(t.btts)}</b></div></div>`}
function rows(arr,empty){if(!arr?.length)return `<div class="empty">${empty}</div>`;return arr.map(x=>`<div class="row"><span>${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('')}
function tableTeam(s){return `<div class="row"><span>${esc(s?.team||'Team')}</span><b>#${esc(s?.rank||'—')} · ${esc(s?.points||'—')} pts</b></div>`}
function source(n,v){return `<div class="row"><span>${n}</span><b class="${v?'green':'red'}">${v?'READY':'NO DATA'}</b></div>`}
async function load(){ $('#content').innerHTML='<div class="loading"><div class="spinner"></div><b>RUSTAM ENGINE</b><span>Получаем реальные данные…</span></div>';try{let url=fixture?`/api/match?fixture=${encodeURIComponent(fixture)}`:'/api/match';let r=await fetch(url);if(!r.ok)throw Error('API '+r.status);DATA=await r.json();updateHeader();render(active)}catch(e){$('#content').innerHTML=`<div class="empty">Не удалось получить данные.<br><small>${esc(e.message)}</small></div>`}}
function updateHeader(){if(!DATA?.fixture)return;$('#title').textContent=`${DATA.fixture.home} — ${DATA.fixture.away}`;$('#subtitle').textContent=DATA.fixture.league||'Football Intelligence';$('#homeName').textContent=DATA.fixture.home;$('#awayName').textContent=DATA.fixture.away;$('#homeLogo').src=DATA.fixture.homeLogo||'';$('#awayLogo').src=DATA.fixture.awayLogo||'';$('#kickoff').textContent=DATA.fixture.time||'—';$('#dateText').textContent=DATA.fixture.status||'PRE-MATCH';$('#venue').textContent=DATA.fixture.venue||'Match intelligence';$('#fixtureId').textContent=`ID ${DATA.fixture.id}`}
document.querySelector('#tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b)render(b.dataset.tab)});$('#refresh').onclick=load;load();
