const tg=window.Telegram?.WebApp;
if(tg){tg.ready();tg.expand();tg.setHeaderColor('#08090D');tg.setBackgroundColor('#08090D')}
const $=s=>document.querySelector(s);let DATA=null;let active='overview';
const params=new URLSearchParams(location.search);const fixture=params.get('fixture')||tg?.initDataUnsafe?.start_param||'';
function esc(v){return String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function pct(v){return v==null?'—':`${Math.round(Number(v))}%`}
function num(v){return v==null?'—':Number(v).toFixed(2)}
function resultClass(x){return x==='W'?'w':x==='L'?'l':x==='D'?'d':''}
function winner(p){const vals=[['П1',p?.home],['Ничья',p?.draw],['П2',p?.away]].filter(x=>x[1]!=null).sort((a,b)=>b[1]-a[1]);return vals[0]||null}
function quality(d){return Math.round(Object.values(d.sources||{}).filter(Boolean).length/5*100)}
function source(name,ok){return `<div class="row"><span>${name}</span><b class="${ok?'green':'red'}">${ok?'ГОТОВО':'НЕТ ДАННЫХ'}</b></div>`}
function rows(arr,empty){if(!arr?.length)return `<div class="empty">${empty}</div>`;return arr.map(x=>`<div class="row"><span>${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('')}
function teamForm(t){if(!t)return '<div class="formteam"><b>Нет данных</b></div>';const r=(t.results||[]).map(x=>`<span class="result ${resultClass(x)}">${x==='W'?'В':x==='L'?'П':'Н'}</span>`).join('');return `<div class="formteam"><b>${esc(t.name)}</b><div class="results">${r||'—'}</div><div class="row"><span>Среднее голов</span><b>${num(t.avgGoals)}</b></div><div class="row"><span>Обе забьют</span><b>${pct(t.btts)}</b></div></div>`}
function tableTeam(s){if(!s)return '<div class="empty">Позиция команды в таблице недоступна.</div>';return `<div class="table-team"><span class="rank">#${esc(s.rank)}</span><div><b>${esc(s.team)}</b><small>Позиция в лиге</small></div><strong>${esc(s.points)} очк.</strong></div>`}
function factors(d){const p=d.prediction||{},out=[];if(p.advice)out.push(['🎯','Прогноз',p.advice]);if(d.home?.results?.length&&d.away?.results?.length)out.push(['📈','Текущая форма',`${d.home.results.join(' · ')}  против  ${d.away.results.join(' · ')}`]);if(d.home?.standing&&d.away?.standing)out.push(['🏆','Положение в лиге',`#${d.home.standing.rank} против #${d.away.standing.rank}`]);if(d.h2h?.count)out.push(['🤝','Очные встречи',`${d.h2h.count} предыдущих матчей`]);if(d.odds?.rows?.length)out.push(['💰','Рынок',`${d.odds.rows.length} линий доступны`]);if(!out.length)return '<div class="empty">Недостаточно данных для факторов.</div>';return out.slice(0,5).map(x=>`<div class="factor"><div class="factor-icon">${x[0]}</div><div><b>${esc(x[1])}</b><span>${esc(x[2])}</span></div><strong>✓</strong></div>`).join('')}
function render(tab){active=tab;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(!DATA)return;const d=DATA;let h='';
if(tab==='overview'){const p=d.prediction||{},win=winner(p),modelled=win&&p.home!=null&&p.draw!=null&&p.away!=null;h=`<div class="grid"><div class="card hero-signal wide"><div class="signal-line"><div><span class="label">ALMAZSTAT · ПРОГНОЗ</span><div class="signal-title">${esc(p.advice||'Недостаточно данных')}</div><p class="signal-copy">${esc(p.note||'Аналитика использует доступные данные API-Football. Отсутствующие значения не подменяются.')}</p></div>${modelled?`<span class="signal-badge">ЛУЧШИЙ СИГНАЛ · ${esc(win[0])}</span>`:''}</div><div class="prob-grid"><div class="prob ${win?.[0]==='П1'?'primary':''}"><b>${pct(p.home)}</b><span>${esc(d.home?.name||'Хозяева')}</span></div><div class="prob ${win?.[0]==='Ничья'?'primary':''}"><b>${pct(p.draw)}</b><span>Ничья</span></div><div class="prob ${win?.[0]==='П2'?'primary':''}"><b>${pct(p.away)}</b><span>${esc(d.away?.name||'Гости')}</span></div></div></div><div class="card"><span class="label">ОЖИДАЕМЫЕ ГОЛЫ</span><div class="big">${num(p.homeGoals)} : ${num(p.awayGoals)}</div><div class="row"><span>Статус</span><b>${p.homeGoals!=null?'Есть данные':'Нет данных'}</b></div></div><div class="card"><span class="label">ЛИНИЯ ГОЛОВ</span><div class="big">${esc(p.underOver||'—')}</div><div class="row"><span>Обе забьют</span><b>${esc(p.btts||'—')}</b></div></div><div class="card"><span class="label">КАЧЕСТВО ДАННЫХ</span><div class="big">${quality(d)}%</div><div class="bar-list"><div><div class="bar-head"><span>Источники готовы</span><b>${Object.values(d.sources||{}).filter(Boolean).length}/5</b></div><div class="track"><div class="fill good" style="width:${quality(d)}%"></div></div></div></div></div><div class="card wide"><div class="section-head"><h3>Ключевые факторы</h3><span>ПО ДАННЫМ МАТЧА</span></div><div class="factor-list">${factors(d)}</div></div></div>`}
if(tab==='form')h=`<div class="grid"><div class="card wide"><div class="section-head"><h3>Последние 5 матчей</h3><span>ТЕКУЩАЯ ФОРМА</span></div><div class="formrow">${teamForm(d.home)}${teamForm(d.away)}</div></div><div class="card"><span class="label">${esc(d.home?.name)} · ГОЛЫ</span><div class="big">${num(d.home?.avgGoals)}</div><div class="row"><span>Обе забьют</span><b>${pct(d.home?.btts)}</b></div></div><div class="card"><span class="label">${esc(d.away?.name)} · ГОЛЫ</span><div class="big">${num(d.away?.avgGoals)}</div><div class="row"><span>Обе забьют</span><b>${pct(d.away?.btts)}</b></div></div></div>`;
if(tab==='h2h')h=`<div class="grid"><div class="card wide"><div class="section-head"><h3>Очные встречи</h3><span>${d.h2h?.count||0} МАТЧЕЙ</span></div>${rows(d.h2h?.rows,'История очных встреч недоступна.')}</div></div>`;
if(tab==='table')h=`<div class="grid"><div class="card wide"><div class="section-head"><h3>Положение в лиге</h3><span>ТЕКУЩИЙ СЕЗОН</span></div>${tableTeam(d.home?.standing)}${tableTeam(d.away?.standing)}</div></div>`;
if(tab==='odds')h=`<div class="grid"><div class="card wide"><div class="section-head"><h3>Коэффициенты</h3><span>СНИМОК РЫНКА</span></div>${rows(d.odds?.rows,'Коэффициенты не доступны для этого матча.')}</div></div>`;
if(tab==='risk'){const r=d.risk||{};h=`<div class="grid"><div class="card hero-signal wide"><span class="label">ОЦЕНКА РИСКА</span><div class="signal-title">${esc(r.level||'НЕДОСТАТОЧНО ДАННЫХ')}</div><p class="signal-copy">${esc(r.reason||'Недостаточно подтверждённых данных.')}</p></div><div class="card wide"><div class="section-head"><h3>Проверка источников</h3><span>5 ПРОВЕРОК</span></div>${source('Прогноз',d.sources?.prediction)}${source('Последняя форма',d.sources?.form)}${source('Очные встречи',d.sources?.h2h)}${source('Таблица лиги',d.sources?.standings)}${source('Коэффициенты',d.sources?.odds)}</div></div>`}
$('#content').innerHTML=h||'<div class="empty">Раздел пока пуст.</div>'}
function updateHeader(){if(!DATA?.fixture)return;const f=DATA.fixture;$('#title').textContent=`${f.home} — ${f.away}`;$('#subtitle').textContent=f.league||'Футбольная аналитика';$('#league').textContent=(f.league||'ФУТБОЛ').toUpperCase();$('#homeName').textContent=f.home;$('#awayName').textContent=f.away;$('#homeLogo').src=f.homeLogo||'';$('#awayLogo').src=f.awayLogo||'';$('#kickoff').textContent=f.time||'—';$('#dateText').textContent=f.status||'ПЕРЕД МАТЧЕМ';$('#venue').textContent=f.venue||'Данные о стадионе';$('#fixtureId').textContent=`МАТЧ ${f.id}`}
async function load(){if(!fixture){$('#content').innerHTML='<div class="error-box"><b>Матч не выбран</b>Открой Mini App из Telegram после выбора матча.</div>';return}$('#content').innerHTML='<div class="loading"><div class="spinner"></div><b>ALMAZSTAT</b><span>Собираем матч-пакет…</span></div>';try{const r=await fetch(`/api/match?fixture=${encodeURIComponent(fixture)}`,{cache:'no-store'});const body=await r.json().catch(()=>({}));if(!r.ok)throw Error(body.error||`API ${r.status}`);DATA=body;updateHeader();render(active)}catch(e){$('#content').innerHTML=`<div class="error-box"><b>Не удалось собрать матч-пакет</b>${esc(e.message||'Неизвестная ошибка')}<br><br><small>Нажми ↻, чтобы повторить запрос.</small></div>`}}
document.querySelector('#tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b)render(b.dataset.tab)});$('#refresh').onclick=load;load();